spring:
  application:
    name: resume-tailor

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  profiles:
    active: local

#  config:
#    import: "optional:file:.env[.properties]"

#openai:
#  api-key: ${OPENAI_API_KEY}
#  model: gpt-4o